### ISSUE TITLE
apply not working with and or or identifier

### ISSUE THREAD

**Issue by FrickTob** [slag-plt/scamper#48]
In trying to make some mentor session practice problems, I am getting an error when I try to use apply with and. Example listed below.

(and #t #t #t) -> returns true
(apply and (list #t #t #t)) -> throws an error "Parser error [63:17-63:18]: Cannot use reserved word as identifier name: and"

**Comment by psosera** [comment]
Unfortunately, it turns out this is an intended feature of Scheme! `and` and `or` are special forms, _i.e._, they do not evaluate like regular function calls. Specifically, they possess _short-circuiting behavior_ where evaluation of an `and`/`or`'s arguments stops once one of the arguments evaluates to `#f`/`#t`, respectively. For example, `(and #f e) --> #f` no matter what `e` is, so Scheme does not evaluate `e` since it evaluates `#f` first. This is analogous to the standard `&&` and `||` operators found in C-like languages.

The work-around is to wrap `and` and `or` in a `lambda` to obtain standard evaluation semantics. This is also called _eta-expansion_ in the literature:

~~~racket
; my-and is a standard function with standard left-to-right sematics
(define my-and
  (lambda (b1 b2) (and b1 b2)))
~~~

Note that since Scamper is (for the most part) pure, we can only tell the difference between short-circuiting and standard evaluation in the presence of infinite loops:

~~~racket
(define loop
  (lambda (x) (loop x)))

; Short-circuiting behavior means we do not evaluate the infinite loop
(display (and #f (loop 0)))

; Standard evaluation means we will evaluate the infinite loop before
; evaluating the body of the function
(display (my-and #f (loop 0)))
~~~
